### PR TITLE
Add minimum duration time

### PR DESCRIPTION
**Pull request by RafaG**
Add minimum duration time in minutes to main filter. For example, I don't want to see charges below 60 minutes.

### CODE REVIEW

**Review by roadrash2108 — APPROVED** [review]
I really like this one! IMHO there should be a maximum filter as well.

**Comment by RafaG** [comment]
> I really like this one! IMHO there should be a maximum filter as well.

In my opinión, current "min voltage" filter has no sense in this dashboard, I think should be removed. Add a maximum duration filter is so easy, if you want it, I can do it

**Comment by roadrash2108** [comment]
> > I really like this one! IMHO there should be a maximum filter as well.
> 
> In my opinión, current "min voltage" filter has no sense in this dashboard, I think should be removed. Add a maximum duration filter is so easy, if you want it, I can do it

I must admit I didn't get the point of having "min voltage", but when looking in the explanation of #857 then it makes sense for me ("Added filter for voltage to allow user to filter down to for example, superchargers.").

In my opinion a feature shouldn't be removed because it doesn't make sense for yourself, as the feature was added for a specific reason. It could be discussed within an issue to remove it, if it really should be removed - for this specific feature I don't see the problem of having more filter as (at least for my devices where I use the dashboards) enough space is left...

Regarding the "maximum voltage" - either you or me can add it. As you prefer!

**Comment by RafaG** [comment]
> I must admit I didn't get the point of having "min voltage", but when looking in the explanation of #857 then it makes sense for me ("Added filter for voltage to allow user to filter down to for example, superchargers.").

Great, I understand now why this filter exists, thanks you
 
> Regarding the "maximum voltage" - either you or me can add it. As you prefer!

I have limited access now, I prefer if you add it

Regards

**Review by adriankumpf — APPROVED** [review]
Looks good to me. Thanks!

A filter for maximum duration would make sense too. The labels should then perhaps be updated (shorter description) to make it look a bit more organized.

**Comment by roadrash2108** [comment]
I just wanted to add the maximum duration filter and streamline the labels, but realized, that I don't have the latest changes as this PR isn't merged. Wouldn't it be easier if @RafaG adds it to his repo and then add the commit to this PR? If not, what would be the right approach for me? (forking RafaG:patch-1?)

Thanks for clarification and sorry for possible git-noob-question ;)

**Comment by adriankumpf** [comment]
Ah, I just realized that #1016 already added the minimum duration filter. So the changes are now on the master branch. I'll close this one. Nevertheless, thanks for the contribution, @RafaG!

**Pull request closed without merging**
