### PR TITLE
postgres to alpine and runs on to latest ubuntu

### PR DESCRIPTION
**Pull request by tobiasehlert**
- appending _-alpine_ to postgres in various doc-files and [.github/workflows/elixir.yml](https://github.com/adriankumpf/teslamate/blob/master/.github/workflows/elixir.yml) (ref #1569)
- switching to `ubuntu-latest` instead of `ubuntu-18.04` for [.github/workflows/elixir.yml](https://github.com/adriankumpf/teslamate/blob/master/.github/workflows/elixir.yml)

### CODE REVIEW

**Comment by adriankumpf** [comment]
I've reverted the commit that bumps the ubuntu image to `latest`. It does not seem to be compatible with the `setup-elixir` action and I'd prefer to use `20.04` instead of `latest`. Will change this in a separate commit.

**Review by adriankumpf — APPROVED** [review]
👍

**Comment by tobiasehlert** [comment]
@adriankumpf looks like the _ubuntu-latest_ was reverted to _ubuntu-18.04_ but the _postgres:13-alpine_ part for postgres was not applied.
Want me to create a separate PR for that? :)

**Comment by adriankumpf** [comment]
Hi @tobiasehlert, unfortunately the alpine images don't work on the Raspberry Pi because its package
sources contains an old version of libseccomp, which causes the time to be at 1970. I had to revert it in 6cfb2a24cf2a04d75f941f35c3950d9055cad919.

**Comment by tobiasehlert** [comment]
> Hi @tobiasehlert, unfortunately the alpine images don't work on the Raspberry Pi because its package
> sources contains an old version of libseccomp, which causes the time to be at 1970. I had to revert it in [6cfb2a2](https://github.com/adriankumpf/teslamate/commit/6cfb2a24cf2a04d75f941f35c3950d9055cad919).

Ah alright! I thought it was only the builder part that broke things.. but oke :)

**Pull request merged**
