### PR TITLE
Geofence updates

### PR DESCRIPTION
**Pull request by Ed-M72**
Enhanced the geofences table, added the following fields:

Active - Is this record active
provider - Network provider of the charger
Supercharger - Is this record a supercharger, this is to overcome the issue in #1516
country code - Specifies the country of the geofence
currency code - specifies the charge currency.

In addition to this four new master data tables have been created to support this currencies & countries, with accompanying language tables for each.

The foreign key between charging_processes and geofences has been altered as there was an issue that allowed geofences that were already in use to be deleted, and therefore affecting historical data.  The foreign key constraint is now set to restrict, and therefore the record can only be deleted if it is unused.  To support this further the active flag has been introduced to distinguish between active and deactivated geofence records.

The teslamate_web live page has been updated for geofences, along with the schema and changeset to allow the new data to be validated and saved.  Error handling has been added to the frontend fields to ensure the user is prompted of any issues.

@adriankumpf - I need you to do one piece of coding to fully bring this to life.  The logic for the active and supercharger fields needs adding into log.ex.  I have tried to understand the code but it is beyond me.  Please could you update it on my behalf.

Active flag
Effectively the logic should be that geofences are only used if the active = true, that is a new charging process should only ever map to an active geofence

Supercharger
the case statement should read something like:
case (if fast_charger_type = "Tesla" and free_supercharging = true)
               then cost = 0.0
       else  (if geofence = supercharger and free supercharging = true)
               then cost = 0.00
      else calculate the cost from the geofence

The new fields can then be used to improve the existing dashboards and bring a bit more granularity to them.
Ed

### CODE REVIEW

**Comment by Ed-M72** [comment]
@adriankumpf  - Ready for re-checking. Ed

**Comment by adriankumpf** [comment]
I see that you have merged the changes from #1562 into this branch. Can we keep these two PR's separate? It's hard to track what this PR changes and what comes from the other.

**Comment by Ed-M72** [comment]
> I see that you have merged the changes from #1562 into this branch. Can we keep these two PR's separate? It's hard to track what this PR changes and what comes from the other.

This is a legacy to me learning Github, this is a separate branch that is kept up to date from the master.  Ideally once #1562 is checked in I will no longer use the master for any further development, and just use branches.

**Comment by Ed-M72** [comment]
@adriankumpf - I found an issue last night, for some reason I can only edit geofences not create/change them.  Will check later to see if it is caused by a code error or by a DB authorisation error after a Postgres upgrade at the weekend.  I expect to do one final commit to this later this week.

**Comment by adriankumpf** [comment]
All right, let's get #1562 merged first then.

**Comment by Ed-M72** [comment]
Re-checked and it was a database schema permissions error stemming from a data restore from backup.  Re-tested and no coding changes needed.  Ready for you to re-check.

**Comment by Ed-M72** [comment]
Closed to allow the fork to be re-adjusted.

**Pull request closed without merging**
