### PR TITLE
Add Docker update documentation

### PR DESCRIPTION
**Pull request by fatbasstard**
This PR adds some minor documentation about updating TeslaMate when installed with Docker.

This to help out with updating it when people are not too familiar with Docker.

### CODE REVIEW

**Review by adriankumpf — APPROVED** [review]
Thank you 👍

**Comment by cwanja** [comment]
Consider compressing it into a single line? 
`
docker-compose down && docker system prune && docker-compose pull && docker-compose up -d
`
Not sure the prune is necessary, but I include it.

**Comment by cwanja** [comment]
Might want to also edit this one. 
https://docs.teslamate.org/docs/upgrading

**Comment by DrJohnM61** [comment]
> Consider compressing it into a single command? 
> 
> `
> 
> docker-compose down && docker system prune && docker-compose pull && docker-compose up -d
> 
> `
> 
> Not sure the prune is necessary, but I include it.

The prune should logically go after the pull as it will clean up and redundant images created by pulling new (updated) images

**Comment by cwanja** [comment]
Excellent, thanks for that feedback. Will update my own script. 

Sent from my iPhone
Chris Wanja
chris.wanja@mac.com
713.444.6999

**Comment by binaryPUNCH** [comment]
Isn't the prune risky to run in between docker-compose down and docker-compose up -d? Won't it delete your data? I ran prune as a final step instead.

**Comment by cwanja** [comment]
> Isn't the prune risky to run inbetween `docker-compose down` and `docker-compose up -d`? Won't it delete your data?
> 
> Use this instead: `docker-compose down && docker-compose pull && docker-compose up -d && docker system prune`

Never had a data loss issue with the `docker system prune` erasing data. But I am open to more suggestions and advice. Am not a Docker expect by any stretch.

**Comment by roadrash2108** [comment]
It's already merged, but I wonder why the information is duplicated as it is in https://github.com/adriankumpf/teslamate/blob/master/website/docs/installation/docker.md and https://github.com/adriankumpf/teslamate/blob/master/website/docs/upgrading.mdx !?

IMHO this should be referenced in the installation-documentation, but not duplicated...

**Pull request merged**
