### PR TITLE
Created an overview dashboard for Grafana

### PR DESCRIPTION
**Pull request by DBemis**
Here is a screenshot of this dashboard: https://i.imgur.com/3Q4UP7U.png

Since this is my first attempted contribution, I assume it will need some tweaks. Everything should be using the car, distance, and temperature units from the vars. I wanted variable thresholds for the temp and voltage gauges, but it appears Grafana doesn't support that feature

This was based on the ideas from some other dashboards I've seen (primarily, https://i.redd.it/hc7v6ts1qni31.jpg ).

### CODE REVIEW

**Comment by ngardiner** [comment]
Just imported into my installation, looks great!

https://imgur.com/a/qZ3Ap43

I use metric units so I'd convert that for my environement, this is a really useful contribution @DBemis

**Comment by adriankumpf** [comment]
Awesome, well done! Thanks @DBemis

One little piece is missing before this can be merged: could you wrap all panels in a "row" that gets repeated for all `$car`s? That way users with multiple cars would see all information in one dashboard. That's how it's done for the other dashboards.

**Comment by spacecosmos** [comment]
Wow! This looks great @DBemis and @ngardiner. How can I get this dash imported? Or will it be included in future releases perhaps @adriankumpf? (I'm sorry for the lack of knowledge here...) :)

**Comment by krezac** [comment]
@spacecosmos I don't have admin password here (so I'm not sure about exact page or field names), but roughly: go to Manage > Dashboards, there is sth like Add JSON, copy the content of the file (overview-dash.json) into the box and save.

**Comment by tucopup** [comment]
Overview dashboard (love it!): only shows 1 vehicle, unclear how to switch to the other Teslas on the account.  Perhaps either the whole dashboard should be repeated per vehicle (like "charges"), or a vehicle selector dropdown in the header row (like "charge details").

**Comment by DBemis** [comment]
> Overview dashboard (love it!): only shows 1 vehicle, unclear how to switch to the other Teslas on the account. Perhaps either the whole dashboard should be repeated per vehicle (like "charges"), or a vehicle selector dropdown in the header row (like "charge details").

Strange - the rows should repeat per vehicle. I'll test adding a fake second car to my local setup this weekend to see what's up

**Comment by tucopup** [comment]
In case it helps: It shows my car ID #2 (of 3).  When I hover over the car name, a gear and trashcan appear.  The gear shows: 
gear
But you can probably see that already.

**Comment by natrlhy** [comment]
Where is this cool new dashboard?

**Comment by bahree** [comment]
In grafana, if you go to Dashboards --> Manage --> Teslamate and then choose the Overview Dash. Attached are a few screenshots showing this.

Capture-1
Capture-2
Capture-3

**Comment by natrlhy** [comment]
Hm I see this:

**Comment by Allram** [comment]
Did a hacking here and managed to get it to work with multiple cars.
Changed the "car"-variable to "car_id".
Atleast now you can switch between the two cars.
[Overview Dash Multiple cars.zip](https://github.com/adriankumpf/teslamate/files/3721115/Overview.Dash.Multiple.cars.zip)

**Comment by adriankumpf** [comment]
Found the fix: The option "Multi-Value" must be activated.

**Comment by DrMichael** [comment]
I would like a visualisation of the state in this view...

**Pull request merged**
