### PR TITLE
Battery Health Grafana Dashboard

### PR DESCRIPTION
**Pull request by jheredianet**
I got my own [TeslaMate Custom Dashboards](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/) where there are several dashboards for my own use, but I decided to share them with people and friends who could be interested in use them. Those dashboards are called: Battery Health, Charging Costs Stats, Charging CurveStats, Current State, Mileage Stats and Tracking Drives. There are also two dashboards (Current Charge & Drive View) that could be browsed on the car while driving or charging.

In this pull request I want to merge to TeslaMate the **Battery Health** dashboard that I am especially proud of, since the initial idea came some years ago from when I had a Hyundai Kona EV from which I logged the data with from a ODB2 scanner ([OVMS](https://www.openvehicles.com/)) and saved in [Influxdb](https://www.influxdata.com/) to visualize them with Grafana. From there, the original idea of generating a dashboard that allows me to check the battery health was born. The calculations were not easy, but over time I could refine them. Now that I have a Tesla and use TeslaMate, I realize that a chart of this type was also needed, so I adapted it without much effort thanks to the amount of data that TeslaMate logs.

This dashboard is meant to have a look of the Battery health based on the data logged in Teslamate. So, **the more data you have logged from your brand-new car the better**, both for degradation and cycle estimations. 

Degradation is just an estimated value to have a reference, measured on usable battery level of every charging session in the last month with enough kWh added (in order to avoid dirty data from the sample), calculated according to the rated efficiency of the car. Then you can see the mileage logged in Teslamate and an estimation of the number of cycles of the battery. On the other hand, you'll see a plotly chart that represents the evolution of the car's battery capacity during its entire lifetime.

Lately I've changed subqueries to INNER JOINS in order to get better performance. It has reduced from 10s to 2s on loading some panels with lot of estimations.

Finally, there is an important improvement for those who have not used Teslamate since they got their car, or for those who have bought it second hand. Now it is possible to set the max range to 100% and the battery capacity of the car battery when it was new in order to get an accurate and better estimation. 

bh

I hope you consider including this contribution into the main project.

Regards,

### CODE REVIEW

**Comment by SiNaPsEr0x** [comment]
please integrate this @adriankumpf

**Comment by KolEll01** [comment]
It will be extremely useful. Add this Adrian please.

**Comment by jheredianet** [comment]
Hi Folks,

With great pride, I want to announce that my repository with [TeslaMate Custom Dashboards](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/)  has been considered among the 5 finalists in the Grafana Golden Grot Awards, celebrating a decade of Grafana dashboards. If you like this project, please, Vote now! Polls close at 11:59 p.m. PDT on Friday, May 5.

[TeslaMate electric vehicle monitoring dashboard (Juan Carlos Heredia)](https://grafana.com/golden-grot-awards)

[TeslaMate electric vehicle monitoring dashboard (Juan Carlos Heredia)](https://grafana.com/golden-grot-awards)

**Review by adriankumpf — APPROVED** [review]
Fantastic work! ❤️ Thank you very much.

**Comment by jheredianet** [comment]
> Fantastic work! ❤️ Thank you very much.
@adriankumpf 
Thank you for the great job on making up Teslamate!!!!

**Comment by KrzysztofHajdamowicz** [comment]
There is an issue with projects.md, a bunch of documentation is deleted with this PR.

**Comment by jheredianet** [comment]
They are not deleted, there were just sorted in alphabetical order.

**Comment by cwanja** [comment]
Holy smokes, this is beautiful @jheredianet

**Comment by DumSkidderik** [comment]
For some reason it reports my P85D to have 94kwh new capacity?

**Comment by jheredianet** [comment]
> For some reason it reports my P85D to have 94kwh new capacity?

Remember this is just an estimation, not a reading from the Car. For some reason your data logged in Teslamate some MaxRange and its calculated from it. I could be many reasons:
- Maybe data you imported from other logger systems.
- Maybe a manual input in the database
- May an uncompleted charging session. 

If you can query your database, you may find where is the record that is giving you the max range, somo of them are treated here https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/issues/38

Anyway, if you know exactly what is your battery capacity and the range when the car was new, you could put those values in the top to tune the estimations. 

image

**Comment by DumSkidderik** [comment]
> Remember this is just an estimation, not a reading from the Car. For some reason your data logged in Teslamate some MaxRange and its calculated from it. I could be many reasons:
> 
> * Maybe data you imported from other logger systems.
> * Maybe a manual input in the database
> * May an uncompleted charging session.
It does include old data from Teslafi, hmmmm

I can't really remember where the import cuts, but ther's a sudden drop in the curve that could maybe explain it
brave_Z8cUu8XsP4

**Comment by jheredianet** [comment]
> I can't really remember where the import cuts, but ther's a sudden drop in the curve that could maybe explain it.
> Then again, I'm pretty sure the Teslafi data is the relatively few samlepoints early on, as soon as the samling interval gets more frequent I'll assume that's Teslamate using the streaming API?

Yes sure, Teslamate uses the streaming API (based in your settings) and more data is logged. 

image

**Comment by gym22** [comment]
> For some reason it reports my P85D to have 94kwh new capacity?

Interestingly, my S 85 shows the same 94kWh capacity. Car is 9 years old but only started using teslamate about 3 years ago. No data was imported from other loggers and no manual input.

image

The projected range dashboard estimates 355km for this car, which is pretty accurate, but battery health shows 445. 

I'll try to follow https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/issues/38 and report what I find.

**Comment by EmilienMathieu** [comment]
> Anyway, if you know exactly what is your battery capacity and the range when the car was new, you could put those values in the top to tune the estimations.
> 
> image

Is it possible to save these 2 parameters ?

**Comment by Emilien-M** [comment]
> Anyway, if you know exactly what is your battery capacity and the range when the car was new, you could put those values in the top to tune the estimations.
> 
> image

Is it possible to save these 2 parameters ?

**Comment by jheredianet** [comment]
> > Anyway, if you know exactly what is your battery capacity and the range when the car was new, you could put those values in the top to tune the estimations.
> > image
> 
> Is it possible to save these 2 parameters?

No, but there is a work around discussed here https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/discussions/53#discussioncomment-6944706

**Comment by enoch85** [comment]
Just want to chime in and say GREAT WORK! Really really appreciated!

**Comment by jheredianet** [comment]
> Just want to chime in and say GREAT WORK! Really really appreciated!

Thank you for your feedback. Enjoy!!! 😊

**Pull request merged**
