### PR TITLE
Using timerange in "Charging Stats" dashboard

### PR DESCRIPTION
**Pull request by nnoally**
Hi,
I think Charging stats dashboard would be more usefull if it use the timerange filter (and even more when charge cost will be enabled).

### CODE REVIEW

**Comment by adriankumpf** [comment]
Thank you! Will merge soon.

**Comment by nnoally** [comment]
You're welcome. Thanks for your great work.

**Comment by adriankumpf** [comment]
I've made one minor change and increased default time range to 'Last 10 years' because most people presumably want to see the long-term statistics first.

**Comment by bahree** [comment]
I pulled the latest and sorry if this is obvious - where do I enter the charging cost for it to show in the dashboard? E.g. most of my charging is at home and I can't figure out where do I add the cost per KWh from my utility? 

Thanks.

**Pull request merged**
