### PR TITLE
Add French Translation

### PR DESCRIPTION
**Pull request by tomS3210**
Add French Translation to Teslamate

### CODE REVIEW

**Comment by adriankumpf** [comment]
Thank you, Thomas!

**Comment by tomS3210** [comment]
Thank for the merge. Where can we choose the langage ?

Thomas

**Comment by adriankumpf** [comment]
If you're running the master branch, it'll automatically pick the preferred language of your browser. To overwrite this setting add `?locale=fr` to the URL.

**Comment by tomS3210** [comment]
Hello Adrian,

Ho how are you ?

I can see that you did a very good job on TeslaMate ! This Streaming API seems to be a very good idea !  
What is the principle ? Teslamate subscribe to the API and then the car send the informations ?
So there is no more pulling every 5 seconds ?

I just send you an update of the French Translation.

How can I update to the new 1.9 Dev version ?

Thanks again for your work.

Regards

Thomas
www.club-tesla.fr <http://www.club-tesla.fr/>

**Pull request merged**
