### PR TITLE
[WIP] readthedocs

### PR DESCRIPTION
**Pull request by gundalow**
Preview: https://teslamate.readthedocs.io/

Every time I looked at the documentation I found something new. There is lots of good content in here that I didn't think was that discoverable. So I wondered if readthedocs could help

#### Sections
I've broken the docs into these sections:
* Getting Started
* Sleep configuration
* Integrations
* Advanced configuration
* Development and Contribution

#### Changes

* Basic readthedocs/Sphinx support
  * sphinx-markdown-tables for the table of environment variables
  * `docs/conf.py` only minimal config needed.
* new `docs/index.rst` which is the root page, note that is is RST (ReStructured Text), not markdown. This file is also used to generate the left navigation bar.
* Use native markdown for images (inline HTML didn't work)
* Edit on GitHub link on the top right of every page, hopefully, makes it easier for Contributors
* Update links as needed

### Questions

1. At a high level, does this look OK?
2. Do the sections and their contents seem OK?
3. Do you spot anything wrong with the formatting

### Not done

* Update README.md to point to the new site, can do the later once we are happy
* Still need a careful review of every page to check formatting

### CODE REVIEW

**Comment by adriankumpf** [comment]
Looks really good! I only noticed that on the 'sleep configuration' page the links to the guides need to be updated. 

What else do you think needs to be done before this can be merged? Building the docs on readthedocs.io would be triggered by Webhooks, I suppose?

**Comment by gundalow** [comment]
Excellent, glad you like I'll review more carefully now and tidy up anything else. Thanks for pointing out the broken sleep guide links.

Could you please sign-up to Readthedocs, and let me know your username, so I can give you powers. 

Builds are triggered for every commit. You can be more fancy and have versioned docs, though that might be overly complex for this.

**Comment by adriankumpf** [comment]
> Could you please sign-up to Readthedocs, and let me know your username, so I can give you powers.

Done. It's the same as my GitHub username.

> Builds are triggered for every commit. You can be more fancy and have versioned docs, though that might be overly complex for this.

Cool, that's all we need for now.

**Comment by gundalow** [comment]
@adriankumpf I think think this is good to merge now
a) I've given you admin on readthedocs, see https://readthedocs.org/projects/teslamate/
b) I've fixed the broken links

Once this is merged I'll:
1) Update readthedocs to build from `adriankumpf/teslamate:master` (rather than my repo)
2) Raise a new PR to update the top level `README` to point to the new docsite

**Comment by adriankumpf** [comment]
Thank you!

**Comment by gundalow** [comment]
Excellent, and I see you've updated RTD to build from your repo. Promotion of RTD added in https://github.com/adriankumpf/teslamate/pull/314

**Comment by adriankumpf** [comment]
Yup, I've updated a few section and I'm also experimenting with an alternative theme. Will merge #314 very soon.

**Pull request merged**
