### PR TITLE
Added magic number to charge details grafana board

### PR DESCRIPTION
**Pull request by codingoverdrive**

### CODE REVIEW

**Comment by adriankumpf** [comment]
I don't understand. Could you explain why this "magic number" is needed?

**Comment by codingoverdrive** [comment]
Many older Teslas have been rate limited when Supercharging. Owners see this as a slower charge rate, faster taper and longer charge times.

Prior to update 2019.16.x the average “magic number” for a Model S85 was 120-130, following the update, the number is typically 100-110.

Owners want to know if future updates are reducing the magic number.

Please see https://teslamotorsclub.com/tmc/posts/4504468/ and the messages below it.

**Comment by adriankumpf** [comment]
I see. Since this metric seems to be useful for supercharging sessions and only some owners know how to interpret it I'd suggest to hide it by default, e.g. with a series override on line 91:

```json
        {
          "alias": "Magic Number",
          "hiddenSeries": true
        }
```

With this approach, shift-clicking on "Magic Number" in the legend would display the series.

**Comment by codingoverdrive** [comment]
Sounds sensible.

**Comment by codingoverdrive** [comment]
Maybe a different name for the metric would be better than "magic number". 

What about "SC Factor"?

**Comment by adriankumpf** [comment]
Yeah, that's a good idea 👍

**Pull request closed without merging**
