### PR TITLE
Option to save / retrieve database

### PR DESCRIPTION
**Pull request by Kriss1670**
First contribution and probably not the right way...
Not a code change but just a suggestion to get a way to automatically save database over the local network (NAS) and retrieve it if needed.
Great job by the way !

### CODE REVIEW

**Comment by adriankumpf** [comment]
Hey @Kriss1670, unfortunately I cannot find your change in the list of commits. Did you update the documentation?

**Comment by Kriss1670** [comment]
Hi Adrian,

As I wrote, this was not a modification, just a suggestion... It is probably not the good way to proceed but I’m completely noob ! I’ve just managed to initialize my Pi and proceed with installation.

Sorry if it is not the good way.

**Comment by adriankumpf** [comment]
OK, I see. I'll close this PR then. Please use the aforementioned GitHub Discussion tab for feature ideas.

**Comment by Kriss1670** [comment]
Ok. Thanks for understanding... I’ll improve !

**Pull request closed without merging**
