### PR TITLE
Enable zoom on live view of the car.

### PR DESCRIPTION
**Pull request by bogosj**

### CODE REVIEW

**Comment by silverl** [comment]
@adriankumpf This is a great feature to add. Can you accept this PR?

**Comment by adriankumpf** [comment]
Would it be possible to show the zoom buttons only when hovering (or tapping on mobile devices)? This would allow to preserve the clean appearance while offering advanced features, such as the map zoom.

**Comment by bogosj** [comment]
I'm not sure how to accomplish that. Instead I've changed the options to allow for dragging the map, zooming with scrolling, and zooming with pinch on mobile. Thoughts?

**Comment by adriankumpf** [comment]
I like that better.  The catch is that it becomes harder to scroll on mobile or small touch devices. It may also surprise you if you are scrolling with the mouse wheel and have just accidentally positioned the cursor over the map.

I can imagine that displaying the controls while hovering might be a good middle ground. For example, you could do it like this:

```js
    const map = createMap({
      // ...
      zoomControl: true,
      // ...
    });


    map.removeControl(map.zoomControl);

    map.on('mouseover', function(e) { map.addControl( map.zoomControl ); });
    map.on('mouseout', function(e) { map.removeControl( map.zoomControl ); });
```

**Comment by bogosj** [comment]
Agreed, it's pretty nice this way.

**Review by adriankumpf — APPROVED** [review]
Cool! Thank you.

**Pull request merged**
