### PR TITLE
Improve power values for AC charging. Fix Addrees Name that was not s…

### PR DESCRIPTION
**Pull request by jheredianet**
Power value on AC charging always shows an integer.  With this fix we calculate it from current and voltage to show a more accurate float value.
The location addres was not showing because the panel was configured to show numeric fields, now it explicitly show the correct field.

### CODE REVIEW

**Comment by adriankumpf** [comment]
Cool idea! The AC detection needs some tweaking though:

### before

Screenshot 2022-06-24 at 13 55 03

### after 

Screenshot 2022-06-24 at 13 54 58

Note how the `charger_voltage` fluctuated between 1 and 2.

**Review by adriankumpf — CHANGES_REQUESTED** [review]
.

**Comment by jheredianet** [comment]
> Cool idea! The AC detection needs some tweaking though:
> 
> ### before
> Screenshot 2022-06-24 at 13 55 03
> 
> ### after
> Screenshot 2022-06-24 at 13 54 58
> 
> Note how the `charger_voltage` fluctuated between 1 and 2.

I could not reproduce in my case. I use a Tesla Model 3. On DC charging, charger_voltage is always 2. 
I made the tweak. Could you try it again please?

**Review by jheredianet — COMMENTED** [review]
I could not reproduce in my case. I use a Tesla Model 3. On DC charging, charger_voltage is always 2. 
I made the tweak. Could you try it again please?

**Pull request closed without merging**
