### PR TITLE
Update drives.json

### PR DESCRIPTION
**Pull request by Dulanic**
Added OR end_position.usable_battery_level IS NULL for situations where intermittent LTE issues cause the end_position.usable_batter_level is NULL.. These were low efficiency drives going up extreme elevations in low LTE coverage areas.

image

image

image

### CODE REVIEW

**Comment by DrMichael** [comment]
@Dulanic Are you on grafana:edge? I redid drives.json for Grafana 7. I could need some testing for Fahrenheit und Miles...
[Drives7-1599493320315.zip](https://github.com/adriankumpf/teslamate/files/5183919/Drives7-1599493320315.zip)

**Review by adriankumpf — APPROVED** [review]
Looks good to me. I just pushed a commit which makes the changes to the drives table in the Trip dashboard.

**Comment by adriankumpf** [comment]
@DrMichael do you want to open a WIP pull request for your changes? We do not have to merge it immediately.

**Comment by Dulanic** [comment]
@DrMichael Sorry i haven't looked at any edge stuff yet. Have been pretty slammed lately.

**Pull request merged**
