### PR TITLE
Add dark mode support

### LINKED ISSUE #236: Dark mode on TeslaMate Dashboard
The title kind of says it all. Any way to implement it? :)

I think it would look good with Grafana already being in **dark mode** as well. (Just a thought and not a very important feature of course.)

### PR DESCRIPTION
**Pull request by Niek**
This PR adds dark mode support for the web interface. It enables when the browser indicates dark mode is preferred (using CSS prefers-color-scheme).

### CODE REVIEW

**Comment by Niek** [comment]
Maybe it looks a little bit better if you change the leafletjs tile layer to ``https://tiles.wmflabs.org/bw-mapnik/${z}/${x}/${y}.png``.

**Comment by Niek** [comment]
The extension doesn't seem to be updated recently., maybe it's an idea to fork it.
- Overriding should be quite easy to changing the [mixin](https://github.com/jloh/bulma-prefers-dark/blob/master/sass/utilities/mixins.sass)
- Styling selects should be a matter of adding 1 extra element [style file](https://github.com/jloh/bulma-prefers-dark/tree/master/sass/elements)

**Comment by Niek** [comment]
FYI the extension has received some updates: https://github.com/jloh/bulma-prefers-dark

**Comment by Dulanic** [comment]
FYI, I created a stylus style to make it dark mode. 

https://raw.githubusercontent.com/Dulanic/stylus/main/teslamate.user.css

**Pull request closed without merging**
